"""add app_settings

Revision ID: 578f008d9203
Revises: 312122b318e9
Create Date: 2026-04-24 16:02:46.264941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578f008d9203'
down_revision: Union[str, None] = '312122b318e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_window_start', sa.Integer(), nullable=False),
    sa.Column('send_window_end', sa.Integer(), nullable=False),
    sa.Column('worker_tick_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
