"""add typing_delay_seconds

Revision ID: af400061e73e
Revises: 578f008d9203
Create Date: 2026-04-24 16:51:27.090837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af400061e73e'
down_revision: Union[str, None] = '578f008d9203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typing_delay_seconds', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('typing_delay_seconds')

    # ### end Alembic commands ###
